---
- name: Debug
  ansible.builtin.debug:
    var: cloudstack_minor_version

- name: Set platform/version specific variables
  ansible.builtin.include_tasks: variables.yaml

- name: Install selected packages
  ansible.builtin.include_tasks: install_packages.yaml

- name: Configure database
  ansible.builtin.include_tasks: database.yaml
  when: cloudstack_node_roles is ansible.builtin.contains('database')

- name: Configure secondary storage
  ansible.builtin.include_tasks: secondary_storage.yaml
  when: cloudstack_node_roles is ansible.builtin.contains('secondary_storage')

- name: Configure management
  ansible.builtin.include_tasks: management_service.yaml
  when: cloudstack_node_roles is ansible.builtin.contains('management')

- name: Configure usage service
  ansible.builtin.include_tasks: usage_service.yaml
  when: cloudstack_node_roles is ansible.builtin.contains('usage')

- name: Configure KVM hypervisor.
  ansible.builtin.include_tasks: kvm_hypervisor.yaml
  when: cloudstack_node_roles is ansible.builtin.contains('kvm_hypervisor')
