---
- name: Create exported directory
  ansible.builtin.file:
    name: /export/secondary
    state: directory
    owner: root
    group: root
    mode: '0777'

- name: Export secondary
  ansible.builtin.lineinfile:
    path: /etc/exports
    regex: '^\/export\s'
    line: /export  {{ cloudstack_nfs_clients }}(rw,async,no_root_squash,no_subtree_check)
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart NFS Server

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Ensure the NFS server service is running
  ansible.builtin.service:
    name: nfs-server
    state: started
    enabled: true

- name: Add secondary storage host to inventory
  ansible.builtin.add_host:
    hostname: "{{ inventory_hostname }}"
    groups:
      - __cloudstack_secondary_storage
