---
- name: Restart mysqld
  ansible.builtin.service:
    name: mysqld.service
    state: restarted
    enabled: true

- name: Restart NFS Server
  ansible.builtin.service:
    name: nfs-server.service
    state: restarted
    enabled: true

- name: Restart libvirtd
  ansible.builtin.service:
    name: libvirtd.service
    state: restarted
    enabled: true
